import re
import sys
import pathlib
sys.stdout.reconfigure(encoding="utf-8", errors="replace")
D = pathlib.Path(__file__).resolve().parent.parent
files = {"g17": D/"grammar-sections-1-7.md", "g812": D/"grammar-sections-8-12.md", "wr": D/"writing-strand.md", "add": D/"addendum-gaps.md"}
txt = {k: p.read_text(encoding="utf-8") for k, p in files.items()}
topics = [
 ("SENTENCE: subject/predicate", r"\bpredicate\b"),
 ("SENTENCE: object/complement", r"\bdirect object|indirect object|\bcomplement\b"),
 ("SENTENCE: fragment", r"\bfragment"),
 ("SENTENCE: run-on / comma splice", r"run-on|comma splice"),
 ("SENTENCE: simple/compound/complex", r"compound sentence|complex sentence|compound-complex"),
 ("SENTENCE: independent/dependent clause", r"independent clause|dependent clause|subordinate clause"),
 ("CLAUSE: noun clause", r"noun clause"),
 ("CLAUSE: relative/adjective clause", r"relative clause|adjective clause"),
 ("CLAUSE: defining vs non-defining", r"non-?defining|restrictive"),
 ("CLAUSE: adverb clause", r"adverb(ial)? clause"),
 ("CLAUSE: reduced relative / participle clause", r"reduced relative|participle clause|participial phrase"),
 ("PHRASE: gerund", r"\bgerund"),
 ("PHRASE: infinitive", r"\binfinitive"),
 ("PHRASE: appositive", r"appositive"),
 ("PHRASE: prepositional phrase", r"prepositional phrase"),
 ("SENTENCE TYPES: imperative", r"\bimperative"),
 ("SENTENCE TYPES: exclamative", r"exclamat"),
 ("SENTENCE TYPES: there is/there are", r"there is|there are|existential"),
 ("SENTENCE: word order SVO", r"word order|\bSVO\b"),
 ("NOUN: count vs non-count", r"count(able)? noun|non-?count|uncountable|mass noun"),
 ("NOUN: plurals incl. irregular", r"irregular plural|plural"),
 ("NOUN: possessive 's / of", r"possessive"),
 ("NOUN: compound nouns", r"compound noun"),
 ("NOUN: collective nouns", r"collective noun"),
 ("NOUN: proper/common/abstract", r"proper noun|abstract noun"),
 ("NOUN: nouns as modifiers", r"noun (as )?(adjunct|modifier)|attributive noun"),
 ("ARTICLE: a/an/the", r"\ba/an\b|indefinite article|definite article"),
 ("ARTICLE: zero article", r"zero article|no article"),
 ("ARTICLE: with proper nouns/geography", r"geograph|the (united|river|mountain|ocean)"),
 ("DETERMINER: demonstratives", r"demonstrative"),
 ("DETERMINER: quantifiers general", r"quantifier"),
 ("DETERMINER: some/any/no", r"some/any|\bsome\b.{0,40}\bany\b"),
 ("DETERMINER: much/many/a lot", r"much/many|\bmuch\b.{0,40}\bmany\b"),
 ("DETERMINER: few/little", r"\ba few\b|\bfew\b|\blittle\b"),
 ("DETERMINER: each/every", r"each/every|\beach\b.{0,20}\bevery\b"),
 ("DETERMINER: both/either/neither", r"\beither\b|\bneither\b"),
 ("DETERMINER: all/most/none", r"\bnone of|most of|all of"),
 ("DETERMINER: another/other/others", r"\banother\b|the other\b"),
 ("DETERMINER: enough/plenty/several", r"\benough\b|\bplenty\b|\bseveral\b"),
 ("PRONOUN: subject/object", r"subject pronoun|object pronoun"),
 ("PRONOUN: possessive adj/pronoun", r"possessive (adjective|pronoun|determiner)"),
 ("PRONOUN: reflexive/intensive", r"reflexive"),
 ("PRONOUN: reciprocal", r"reciprocal|each other"),
 ("PRONOUN: relative pronouns", r"relative pronoun"),
 ("PRONOUN: indefinite (somebody, anyone)", r"indefinite pronoun|somebody|anyone|everyone"),
 ("PRONOUN: demonstrative/interrogative", r"demonstrative pronoun|interrogative pronoun"),
 ("PRONOUN: dummy it / empty subject", r"dummy|empty subject|impersonal it|\bit\b as (a )?subject"),
 ("PRONOUN: one/ones", r"one/ones|\bones\b"),
 ("PRONOUN: reference/antecedent agreement", r"antecedent|pronoun reference|ambiguous"),
 ("PRONOUN: generic you/they/one, singular they", r"singular they|generic (you|they|one)"),
 ("VERB: be/have/do", r"\bverb be\b|\bto be\b|\bbe\b as (a )?(main|linking)"),
 ("VERB: present simple", r"present simple|simple present"),
 ("VERB: present continuous", r"present continuous|present progressive"),
 ("VERB: past simple", r"past simple|simple past"),
 ("VERB: past continuous", r"past continuous|past progressive"),
 ("VERB: present perfect", r"present perfect(?! continuous| progressive)"),
 ("VERB: present perfect continuous", r"present perfect (continuous|progressive)"),
 ("VERB: past perfect", r"past perfect(?! continuous| progressive)"),
 ("VERB: past perfect continuous", r"past perfect (continuous|progressive)"),
 ("VERB: will / future simple", r"future simple|simple future"),
 ("VERB: going to", r"going to"),
 ("VERB: present forms for future", r"for (the )?future|timetable|arrangement"),
 ("VERB: future continuous", r"future continuous|future progressive"),
 ("VERB: future perfect", r"future perfect"),
 ("VERB: future in the past", r"future in the past|was going to"),
 ("VERB: used to / would (past habit)", r"used to"),
 ("VERB: be/get used to", r"(be|get) used to"),
 ("VERB: stative verbs", r"stative|state verb|non-?progressive verb"),
 ("VERB: irregular verbs", r"irregular verb"),
 ("VERB: auxiliaries / do-support", r"auxiliar|helping verb|do-support|emphatic do"),
 ("VERB: phrasal verbs", r"phrasal verb"),
 ("VERB: separable/inseparable", r"separable"),
 ("VERB: verb + gerund/infinitive patterns", r"verb pattern|gerund or infinitive|gerund vs|verbs followed by"),
 ("VERB: causatives (have/get/make/let)", r"causative|have (something|it) done|get (someone|somebody) to|make (someone|somebody)"),
 ("VERB: passive voice", r"passive"),
 ("VERB: passive with modals/perfect, get-passive", r"get-passive|get passive|passive (with|and) modal|been \+ past participle"),
 ("VERB: impersonal passive (it is said)", r"it is said|impersonal passive|is thought to"),
 ("VERB: transitive/intransitive", r"transitive"),
 ("VERB: linking verbs", r"linking verb|copular"),
 ("VERB: tense consistency / shift", r"tense (consistency|shift)|sequence of tenses|unnecessary shift"),
 ("VERB: time expressions per tense", r"time expression|signal word|time marker"),
 ("VERB: subjunctive / mandative", r"subjunctive|mandative"),
 ("MODAL: ability/permission/request", r"\bability\b|\bpermission\b"),
 ("MODAL: obligation/advice", r"\bmust\b|have to|\bshould\b|ought to"),
 ("MODAL: possibility/deduction", r"deduction|possibility|might have|must have"),
 ("MODAL: past modals (should have)", r"should have|could have|would have|perfect modal"),
 ("MODAL: semi-modals (need to, had better, be able to)", r"had better|be able to|need to|\bdare\b"),
 ("COND: zero/first/second/third/mixed", r"zero conditional|first conditional|second conditional|third conditional|mixed conditional"),
 ("COND: unless/as long as/provided/in case", r"\bunless\b|as long as|provided|in case"),
 ("COND: wish / if only", r"\bwish\b|if only"),
 ("COND: inversion (had I known)", r"had I\b|were I\b|should you\b|inversion"),
 ("REPORT: reported statements/questions/commands", r"reported (speech|statement|question|command)|indirect speech"),
 ("REPORT: reporting verbs (suggest, advise)", r"reporting verb"),
 ("REPORT: backshift / time-place changes", r"backshift"),
 ("QUESTION: yes/no + wh-", r"yes/no|wh-? ?question"),
 ("QUESTION: subject vs object questions", r"subject question|object question"),
 ("QUESTION: indirect/embedded questions", r"embedded question|indirect question"),
 ("QUESTION: question tags", r"question tag|tag question"),
 ("QUESTION: short answers / so do I", r"short answer|so do i|neither do i"),
 ("NEGATION: not/never/double negatives", r"double negative|negation"),
 ("ADJ: comparatives/superlatives", r"comparative|superlative"),
 ("ADJ: as...as / equality", r"as \.\.\. as|as…as|equal(ity)? comparison"),
 ("ADJ: order of adjectives", r"adjective order|order of adjectives"),
 ("ADJ: -ed vs -ing", r"-ed (vs|and|/) ?-ing|bored/boring|participial adjective"),
 ("ADJ: gradable/ungradable, intensifiers", r"gradable|intensifier"),
 ("ADJ: compound adjectives + hyphens", r"compound adjective"),
 ("ADV: types (manner/place/time/frequency/degree)", r"adverbs? of (manner|frequency|degree|place|time)"),
 ("ADV: position", r"adverb position|position of adverbs|mid-position"),
 ("ADV: adjective vs adverb (good/well, hard/hardly)", r"good/well|hard/hardly|adjective (vs|or) adverb"),
 ("ADV: too/enough", r"too/enough|\btoo\b.{0,30}\benough\b"),
 ("ADV: so/such", r"so/such|\bso\b.{0,30}\bsuch\b"),
 ("ADV: still/yet/already/anymore", r"\byet\b|already|anymore|\bstill\b"),
 ("PREP: time (at/on/in)", r"preposition(s)? of time|at/on/in|in/on/at"),
 ("PREP: place/position", r"preposition(s)? of place"),
 ("PREP: movement/direction", r"movement|direction"),
 ("PREP: for/since, during/while, by/until", r"for/since|during/while|by/until"),
 ("PREP: dependent prepositions (depend on)", r"dependent preposition|verb \+ preposition|adjective \+ preposition|noun \+ preposition"),
 ("PREP: like vs as, between/among, despite", r"like/as|like vs as|between/among|despite|in spite of"),
 ("PREP: preposition at end of question/clause", r"stranding|preposition at the end|end of (a )?(question|clause)"),
 ("CONJ: coordinating (FANBOYS)", r"coordinating|fanboys"),
 ("CONJ: subordinating", r"subordinating|subordinator"),
 ("CONJ: correlative", r"correlative|not only"),
 ("CONJ: conjunctive adverbs / transitions", r"conjunctive adverb|transition"),
 ("CONJ: purpose/result/contrast clauses", r"purpose clause|result clause|so that|in order to|clause of (reason|purpose|result|contrast)"),
 ("COHESION: reference/substitution/ellipsis", r"substitution|ellipsis|cohesion"),
 ("COHESION: parallel structure", r"parallel"),
 ("STYLE: dangling/misplaced modifiers", r"dangling|misplaced modifier"),
 ("STYLE: cleft / fronting / emphasis", r"cleft|fronting|emphatic"),
 ("STYLE: register formal/informal", r"register"),
 ("STYLE: nominalization", r"nominali[sz]"),
 ("STYLE: concision/wordiness", r"wordiness|concise|redundan"),
 ("STYLE: hedging/politeness", r"hedg|politeness|soften"),
 ("PUNCT: comma rules", r"\bcomma\b"),
 ("PUNCT: semicolon/colon", r"semicolon|\bcolon\b"),
 ("PUNCT: apostrophe", r"apostrophe"),
 ("PUNCT: quotation marks", r"quotation mark"),
 ("PUNCT: hyphen/dash", r"hyphen|\bdash"),
 ("PUNCT: parentheses/brackets", r"parenthes|bracket"),
 ("PUNCT: end punctuation", r"end punctuation|question mark|exclamation (mark|point)"),
 ("MECH: capitalization", r"capitali[sz]"),
 ("MECH: spelling rules (-ing, plurals, -ies)", r"spelling"),
 ("MECH: numbers/dates/times", r"\bnumbers\b|numerals|\bdates\b"),
 ("MECH: abbreviations/contractions", r"abbreviation|contraction"),
 ("WORD: confusables (their/there, its/it's)", r"their/there|its/it's|confusable|homophone|commonly confused"),
 ("WORD: prefixes/suffixes/word families", r"prefix|suffix|word famil|word formation"),
 ("WORD: collocations", r"collocation"),
 ("AGREE: subject-verb basics", r"subject-verb agreement"),
 ("AGREE: tricky subjects (collective, either/or, there is)", r"collective|neither \.\.\. nor|either \.\.\. or"),
 ("AGREE: pronoun-antecedent", r"pronoun-antecedent|antecedent agreement"),
]
def count(rx, s): return len(re.findall(rx, s, re.I))
print(f"{'topic':58} {'g1-7':>5} {'g8-12':>5} {'writ':>5} {'add':>4}  flag")
for name, rx in topics:
    c = {k: count(rx, txt[k]) for k in txt}
    g = c["g17"] + c["g812"] + c["add"]
    flag = "MISSING" if g == 0 else ("THIN" if g < 4 else "ok")
    print(f"{name:58} {c['g17']:>5} {c['g812']:>5} {c['wr']:>5} {c['add']:>4}  {flag}")
